### ISSUE TITLE
Problem with examples in documentation (and node 4.4.3)

### ISSUE THREAD

**Issue by Cyber1000** [audreyt/node-webworker-threads#106]
Environment:
Ubuntu LTS 14.04
Node 4.4.3

x. Reproduce:
- new dir
- npm init
- npm install webworker-threads (no problem in output)
- copied the first woker script (at the beginning of README)
- executed with: node {filename}
- works
- Same for example A and B
- worked too
- C didn't work, only get an output from spinforerver (if there is some stdout.write in there), nothing from the callback
- D and other examples I have the same problem too

y. Also tried directly with node-webworker-threads from here:
- git clone {url}
- node-gyp rebuild ("gyp ok" at the end and no error as far I've seen)
- node examples/quickIntro_oneThread.js
- I get an error that module "webworker-threads" is missing, which is somehow obvious

My questions:
- How would I try the examples (x or y)?
- Am I missing something within the examples? As for example "quickIntro_oneThread.js" didn't give me an output in callback. Is my node version not supported?

Any idea?

Thanks!

**Comment by audreyt** [comment]
The examples in README is out of date — it refers to Node 0.9 or earlier.

In Node 0.10 and later (which is the minimum version we support) the preferred syntax is `setImmediate` instead of `process.nextTick` — I fixed all examples and README and made a new release ( 0.7.5 on npm ). Thanks for the catch!
