### ISSUE TITLE
console.log from within worker thread

### ISSUE THREAD

**Issue by logidelic** [audreyt/node-webworker-threads#132]
Is it possible to call console.log from within worker thread's onmessage, as in:

```
var worker = new Worker(function() {
    this.onmessage = function(e) {
        console.log('hello');
        ...
    };
});
...
```
The documentation seems to suggest that this should work (unless I misread) but I don't get any output. onmessage is indeed firing correctly and posts its result (correctly) back to the main thread, but my console logging gets eaten.

Thanks.

**Comment by brodybits** [comment]
This is a missing feature, similar to setTimeout (#50) and setInterval (#110).

**Comment by davisjam** [comment]
How useful of a feature would this be? I think the C++ bindings shouldn't be too hard to cook up. It seems to me that console logging is an easy debugging approach out of which users could get a lot of traction.

Regarding timers: I think #50 and #110  might be best implemented using the same approach that Node.js takes, which is using lbuv's timer APIs. This would require establishing a (fairly lightweight) uv loop in each thread, and the timers would only be triggered when the libuv loop is spun. The libuv loop could be run repeatedly in between the arrival of new tasks.

Brodybits, your thoughts?
Are there other features that need C++ bindings? I'm wondering how much abstraction to bake in.

Also, does TAGG already have this or similar? How much has TAGG changed since audreyt's fork?

**Comment by davisjam** [comment]
Actually, @logidelic, this seems to work for me on commit 0d9a167e11c with node v7.4. I also tried it successfully after running a fresh `npm install`. Can you re-try it with a fresh npm install and tell me how it goes for you? And what version of node you're running?

On the bleeding edge:
```
(16:41:52) jamie@suwarna7-Lenovo-K450e ~/Desktop/node-webworker-threads/examples $ cat x.js
var Threads = require('../index');
var Worker = Threads.Worker;

var worker = new Worker(function() {
    this.onmessage = function(e) {
        console.log('hello');
    };
});

worker.postMessage('hi');
```

yields

```
$ node x.js
hello
```

I get the same result after a fresh `npm install' (changing the require path, but leaving everything else unchanged):

```
var Threads = require('webworker-threads');
...
```

**Comment by logidelic** [comment]
@davisjam Yes! This appears to work now, thanks for pointing out.  👍
