### ISSUE TITLE
xmlhttprequest is not defined?

### ISSUE THREAD

**Issue by lighter697** [audreyt/node-webworker-threads#96]
xmlhttprequest is not working inside webworker function

**Comment by audreyt** [comment]
Indeed. This is Node.js, so XMLHTTPRequest is not provided by default.

(I'd be happy to take a patch.)

**Comment by lighter697** [comment]
But how could I use for example [request](https://www.npmjs.com/package/request) module inside FIBO() function?

It does not want to work inside FIBO scope despite the fact that i have used browserify to concatenate all the scripts to one script and inserted it's path into importScripts() function.
It causes this error ```TypeError: global.XMLHttpRequest is not a function ```

The code looks like this:


INDEX.JS
```
var Threads = require('webworker-threads');
var threadPool = Threads.createPool(10);


function fibo () {
    try {
        importScripts('/opt/lampp/htdocs/crawler2/dist.js');
    } catch (e) {
        return e;
    }
}

threadPool.all.eval(fibo).all.eval('fibo()', function cb (err, data) {
    process.stdout.write(" ["+ this.id+ "]"+ data);
    this.eval('fibo()', cb);
});
```

SRC.JS

```
try {
    var request = require('request');
    request('http://buzler.ru', function (error, response, body) {
        if (!error && response.statusCode == 200) {
            return 'Hello';
        }
    });
    return 'hi';
} catch(e) {
    return e;
}
```

**Comment by audreyt** [comment]
The WebWorker API is primarily designed to run CPU-bound tasks in parallel, because they would be blocking when run in the main thread.

In browser context as well in Node.js, network-bound requests such as XHR are already asynchronous and non-blocking by default, so there is very little to gain from running them in Worker context.

Would you mind try moving the XHR into the main context — or elaborate why it is necessary to run them in Worker context?

**Comment by belohlavek** [comment]
If you try to use something asm.js related inside a webworker in node you will probably need XHR. See https://github.com/kripken/emscripten/blob/master/src/shell.js#L166
